spring:
  io:
    minio:
      username: minioadmin
      password: minioadmin
      host: 114.132.177.185
      port: 9000
      path-prefix:
        video: video
        file: file
        price: price
      bucket-strategy-name:
        private-spire-bucket: false
        public-spire-bucket: true